import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="grid grid-cols-4 min-h-screen">
      <aside className="items-center justify-between p-24 bg-blue-300">
        Dashboard Side Bar
      </aside>
      <section className="col-span-3 items-center justify-between p-24 bg-red-300">
        {children}
      </section>
    </main>
  );
}
